config/routes.rb
Hydra::Application.routes.draw do
  devise_for :admins, skip: [:sessions]
  as :admin do
    root to: "devise/sessions#new"
    get 'sign_in' => 'devise/sessions#new', as: :new_admin_session
    post 'sign_in' => 'devise/sessions#create', as: :admin_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    root to: "projects#index"
    resources :admins
    resources :projects do
      resources :releases
    end

    resources :api_keys
  end

  namespace :api do
    resources :projects do
      resources :releases, defaults: { format: 'json' }
    end
  end

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  # Associations

  # Delegates

  # Validations
  validates :access_token, uniqueness: true

  # Scopes

  # Extensions
  include AASM

  # Callbacks
  before_create :generate_access_token

  # Attributes
  attr_accessible :access_token

  # States
  aasm do
    state :active, initial: true
    state :revoked

    event :revoke do
      transitions from: :active, to: :revoked
    end

    event :activate do
      transitions from: :revoked, to: :active
    end
  end

  def to_param
    self.access_token
  end

  private
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
      end while self.class.exists?(access_token: access_token)
  end
end

app/controllers/admin/api_keys_controller.rb
class Admin::ApiKeysController < Admin::ApplicationController
  before_filter :fetch_api_key, only: [ :edit, :update ]

  def index
    @api_keys = ApiKey.all
  end

  def create
    ApiKey.create
    add_message "An API key was successfully generated."
    redirect_to admin_api_keys_path
  end

  def update
    state_change = params.fetch(:status_change, 'activate')

    @api_key.revoke! if state_change == 'revoke' && @api_key.active?

    @api_key.activate! if state_change == 'activate' && @api_key.revoked?

    add_message "Changed status for API Key #{@api_key.access_token}"

    redirect_to admin_api_keys_path
  end

  private
  def fetch_api_key
    @api_key = ApiKey.where("access_token = ?", params[:id]).first
  end
end

app/helpers/admin/api_keys_helper.rb
module Admin::ApiKeysHelper
end

app/views/admin/api_keys/index.html.erb
<h1>API Keys</h1>

<% if @api_keys.blank? %>
  <p class="text-warning">There are no API keys. Would you like to add one?</p>
  <%= link_to 'Generate an API key', admin_api_keys_path, method: :post, class: "btn btn-success" %>
<% else %>
  <div class="table-actions">
    <%= link_to "Generate an API key", admin_api_keys_path, method: :post, class: "btn btn-primary" %>
  </div>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <td>Access Token</td>
        <td>State</td>
        <td>Created At</td>
        <td>Updated At</td>
      </tr>
    </thead>
    <tbody>
      <% @api_keys.each do |api_key| %>
      <tr>
        <td><%= link_to api_key.access_token, edit_admin_api_key_path(api_key) %></td>
        <td>
          <%= api_key.aasm_state %>
          <%= link_to "#{content_tag(:i, '', class: 'icon-remove-sign')} #{api_key.aasm_events_for_state(api_key.aasm_state.to_sym).first.to_s}".html_safe, admin_api_key_path(api_key, status_change: "#{api_key.aasm_events_for_state(api_key.aasm_state.to_sym).first.to_s}"), class: 'text-error', method: :put %>
        </td>
        <td><%= api_key.created_at %></td>
        <td><%= api_key.updated_at %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>