config/routes.rb
Hydra::Application.routes.draw do
  devise_for :admins, skip: [:sessions]
  as :admin do
    root to: "devise/sessions#new"
    get 'sign_in' => 'devise/sessions#new', as: :new_admin_session
    post 'sign_in' => 'devise/sessions#create', as: :admin_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    root to: "projects#index"
    resources :admins
    resources :projects do
      resources :releases
    end

    resources :api_keys
  end

  namespace :api do
    resources :projects do
      resources :releases, defaults: { format: 'json' }
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  # Associations
  has_many :releases, dependent: :destroy

  # Delegates

  # Validations
  validates :name, presence: true

  # Scopes

  # Extensions
  include AASM
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Callbacks

  # Attributes
  attr_accessible :name

  # States
  aasm do
    state :active, initial: true
    state :archived

    event :archive do
      transitions from: :active, to: :archived
    end

    event :activate do
      transitions from: :archived, to: :active
    end
  end

  def to_param
    self.slug
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :fetch_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @releases = @project.releases.order("deployed_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      add_message "Project was created successfully."
      redirect_to admin_projects_path
    else
      add_error "There was an error creating the project. Please try again."
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      add_message "Project was updated successfully."
      redirect_to admin_projects_path
    else
      add_error "There was an error updating the project. Please try again."
      render :edit
    end
  end

  def destroy
    if @project.destroy
      add_message "Project #{@project.name} was deleted successfully."
    else
      add_error "There was an error deleting project #{@project.name}. Please try again."
    end
    redirect_to admin_projects_path
  end

  protected
  def fetch_project
    @project = Project.find(params[:id])
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/edit.html.erb
<h1>Edit project</h1>

<%= form_for [:admin, @project] do |f| %>
  <fieldset>
    <label>Project name</label>
    <%= f.text_field :name, placeholder: 'Enter a project name', class: "input-xxlarge" %>
    <label>Url name</label>
    <%= f.text_field :slug, class: "input-xxlarge", disabled: true %>
    <label>State</label>
    <%= f.text_field :aasm_state, class: "input-xxlarge", disabled: true %>
  </fieldset>

  <%= f.submit 'Update project', class: 'btn btn-success' %>
  <%= link_to 'Cancel', admin_projects_path, class: 'btn' %>
<% end %>

app/views/admin/projects/index.html.erb
<% if @projects.blank? %>
  <p class="text-warning">No projects have been added.</p>
  <%= link_to 'Add a new project', new_admin_project_path, class: "btn btn-success" %>
<% else %>
  <div class="table-actions">
    <%= link_to "Add a new project", new_admin_project_path, class: "btn btn-primary" %>
  </div>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <td>Project Name</td>
        <td>Number of Releases</td>
        <td>Actions</td>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, admin_project_path(project) %></td>
        <td><%= project.releases_count || 0 %></td>
        <td>
          <%= link_to 'Edit project', edit_admin_project_path(project), class: 'btn btn-primary' %>
          <%= link_to 'Delete project', admin_project_path(project), method: :delete, data: { confirm: 'This will delete the project and all release data. Are you sure you want to delete this project?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/projects/new.html.erb
<h1>Create a new project</h1>

<%= form_for [:admin, @project] do |f| %>
  <fieldset>
    <label>Project name</label>
    <%= f.text_field :name, placeholder: 'Enter a project name', class: "input-xxlarge" %>
  </fieldset>

  <%= f.submit 'Create project', class: 'btn btn-success' %>
  <%= link_to 'Cancel', admin_projects_path, class: 'btn' %>
<% end %>

app/views/admin/projects/show.html.erb
<h1><%= @project.name %></h1>

<h3>Releases</h3>

<div class="table-actions">
  <%= link_to "Add a manual release", new_admin_project_release_path(@project), class: "btn btn-primary" %>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Branch</th>
      <th>Environment</th>
      <th>Deployed At</th>
    </tr>
  </thead>
  <tbody>
    <% @releases.each do |release| %>
    <tr>
      <td class="image"><%= gravatar_image_tag release.admin.email, gravatar: { size: 45 }, class: 'img-circle' %></td>
      <td><%= release.admin.name %></td>
      <td><%= release.branch %></td>
      <td><%= release.environment %></td>
      <td><%= release.deployed_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<hr>

<div id="chart"></div>

<script>
  var data = []
  <% Project.find(@project.id).releases.group_by_month.each do |month, releases| %>
    data.push({month: '<%= month %>', releases: <%= releases %>})
  <% end %>
</script>