config/routes.rb
Hydra::Application.routes.draw do
  devise_for :admins, skip: [:sessions]
  as :admin do
    root to: "devise/sessions#new"
    get 'sign_in' => 'devise/sessions#new', as: :new_admin_session
    post 'sign_in' => 'devise/sessions#create', as: :admin_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    root to: "projects#index"
    resources :admins
    resources :projects do
      resources :releases
    end

    resources :api_keys
  end

  namespace :api do
    resources :projects do
      resources :releases, defaults: { format: 'json' }
    end
  end

end

app/views/admin/admins/index.html.erb
<h1>Admins</h1>

<div class="table-actions">
  <%= link_to "Add new admin", new_admin_admin_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <td>Name</td>
      <td>Created At</td>
      <td>Updated At</td>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
    <tr>
      <td><%= link_to admin.name, admin_admin_path(admin) %></td>
      <td><%= admin.created_at %></td>
      <td><%= admin.updated_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h1>Create a new admin</h1>

<%= form_for [:admin, @admin] do |f| %>
  <fieldset>
    <label>Admin's email</label>
    <%= f.text_field :email, placeholder: 'Enter the admin\'s email. Use this to log in to hydra.', class: "input-xxlarge" %>
    <label>Admin's email aliases</label>
    <%= f.text_field :email_aliases, placeholder: 'Enter the admin\'s email aliases. This should be your email account you use for github.', class: "input-xxlarge" %>
    <label>Admin's first name</label>
    <%= f.text_field :first_name, placeholder: 'Enter the admin\'s first name', class: "input-xxlarge" %>
    <label>Admin's last name</label>
    <%= f.text_field :last_name, placeholder: 'Enter the admin\'s last name', class: "input-xxlarge" %>
  </fieldset>

  <%= f.button "Create admin", class: 'btn btn-success' %>
  <%= link_to 'Cancel', admin_admins_path, class: 'btn' %>
<% end %>

app/views/admin/admins/show.html.erb
<h1><%= @admin.name %></h1>

<h3>details</h3>

<p>Email: <%= @admin.email %> </p>
<p>Email Aliases: <%= @admin.email_aliases %>