config/routes.rb
Hydra::Application.routes.draw do
  devise_for :admins, skip: [:sessions]
  as :admin do
    root to: "devise/sessions#new"
    get 'sign_in' => 'devise/sessions#new', as: :new_admin_session
    post 'sign_in' => 'devise/sessions#create', as: :admin_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    root to: "projects#index"
    resources :admins
    resources :projects do
      resources :releases
    end

    resources :api_keys
  end

  namespace :api do
    resources :projects do
      resources :releases, defaults: { format: 'json' }
    end
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Hydra', admin_projects_path, class: 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Admins', admin_admins_path %></li>
          <li><%= link_to 'API Keys', admin_api_keys_path %></li>
          <li><%= link_to 'Projects', admin_projects_path %></li>
          <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</div>